name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Your Ubuntu system with Docker & Minikube

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's daemon
      run: |
        echo "Switching Docker context to Minikube"
        eval $(minikube docker-env)

    - name: Build frontend Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/book-review-frontend:latest ./frontend

    - name: Build backend Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/book-review-backend:latest ./backend

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push frontend image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/book-review-frontend:latest

    - name: Push backend image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/book-review-backend:latest

    - name: Apply Kubernetes manifests
      run: kubectl apply -f k8s/ --namespace=bookreview
