name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main  # Adjust if your default branch is named differently

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/book-review-backend:latest

    - name: Fix Frontend Dockerfile permissions
      run: chmod -R 755 frontend/

    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/book-review-frontend:latest

    - name: Set up Minikube
      uses: medyagh/setup-minikube@latest

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        kubectl version --client
        echo "PATH=$PATH:/usr/local/bin" >> $GITHUB_ENV

    - name: Deploy to Minikube
      run: |
        minikube status
        kubectl apply -f k8s/
        kubectl get pods --namespace=bookreview
